### ISSUE TITLE
zarr: status vs upload_in_progress

### ISSUE THREAD

**Issue by yarikoptic** [dandi/dandi-archive#1138]
Looking at https://github.com/dandi/dandi-cli/issues/1034#issuecomment-1170086957 from @satra and my grep through the dump of all zarrs we see that that zarr has

```
      "status": "Complete",
      "checksum": "5a3cdb1c9b65e077011e80bbd1003222-255--602198343",
      "upload_in_progress": true,
```

which suggests that upload was not yet completed, but checksum computed, and status marked "Complete".  It seems that we might be having redundant (and thus prone to get out of sync) metadata fields which might cause confusion. E.g. in this case, shouldn't status be "uploading" and avoid having dedicated `upload_in_progress` at all?

**Comment by AlmightyYakob** [comment]
I think I know what's going on.

When uploading, the zarr upload files are created, which each contain a presigned url, that the user uses to upload to S3 directly. The existence of any upload files tied to a zarr is what determines the value of `upload_in_progress`. So when an upload is begun, these upload files (db models) are created, and `upload_in_progress` is true. However, `status` is not set to `Pending` yet, since if the uploads are cancelled, there's no need to ingest; nothing has changed. It's only when the zarr upload complete endpoint is called that the upload file models are deleted from the DB, and the `status` field is set to `Pending`. Then, the ingest endpoint must be called manually to kick off ingestion, and set the status to "Complete".

**Comment by yarikoptic** [comment]
> since if the uploads are cancelled, there's no need to ingest

hm, shouldn't any modification to zarr kick in "ingest"ion process since otherwise information about zarr (checksum etc) would no longer be up-to-date?  if so, even if upload is canceled (which might imply removal of partially uploaded files, or not) - should be reingested, and thus `status` being `Pending` would IMHO would not only be appropriate but pretty much "required" since the state of zarr would be changing during the upload.  Or what am I missing?

**Comment by satra** [comment]
> since if the uploads are cancelled, there's no need to ingest; nothing has changed. 

i concur with yarik. if uploads are are cancelled that doesn't mean state of zarr has not changed.  since uploads are in batches, canceling an upload could happen after something was uploaded. i think a single chunk addition, modification, or deletion would mean state of the zarr has changed. what i don't know is if there is anyway for the server to know one of these events has happened before cancel was called.

**Comment by satra** [comment]
> but I just want clarity that it's the desired behavior.

yes, the technical question is when ingest gets triggered.  
- on upload complete/cancel, but ingest delayed when another upload starts
- on client trigger on ingest (with perhaps an optional force flag)
- on a timeout of some kind if upload is neither completed or canceled

**Comment by satra** [comment]
sorry i didn't know if there was anything happening on the server side. that's fine if it is the client's responsibility.

**Comment by yarikoptic** [comment]
moreover, on client side, as of yesterday we do not trigger ingestion if we did not upload anything (https://github.com/dandi/dandi-cli/pulls?q=is%3Apr+is%3Aclosed) which IMHO makes sense in general.  May be we actually would need to trigger `ingest`, and ignore possible 400 (race condition), if we see that `status` is `Pending` and `upload_in_progress` is `False`.  Is that the right "conditioning" for such a case?

But I dislike that to be demanded from client since that would mean that we will end up with some non-ingested zarrs which we and users would keep encountering.  But because of absent time stamping/logging of actions I do not see any good way to do it some other way, e.g. on some time out ATM.

**Comment by AlmightyYakob** [comment]
It might be good to meet and think about redesigning certain parts of the zarr upload / ingestion process, to ensure consistency and reduce client dependence.

**Comment by AlmightyYakob** [comment]
This is now moot via https://github.com/dandi/dandi-archive/pull/1448, since `upload_in_progress` doesn't exist on zarrs anymore.
