### ISSUE TITLE
Need reliable mechanism to channel back errors from workers

### ISSUE THREAD

**Issue by yarikoptic** [dandi/dandi-archive#1155]
The case of https://github.com/dandi/dandi-archive/pull/1154 fix showed that even in the cases where code misses some required argument, such an error could go unnoticed for days until we just run into some "odd behavior".  But apparently such errors are logged!  Here is a summary for the last days of ERRORs I see in the logs for my probably incomplete dump of heroku logs

```
(base) dandi@drogon:/mnt/backup/dandi/heroku-logs/dandi-api$ grep ERROR 20220{6{2,3},7}* | sed -e 's,.* ERROR,ERROR,g' -e 's,ForkPoolWorker-[12345],ForkPoolWorker-X,g' | sed -E 's,[a-f0-9-]{8}([a-f0-9-]{4}){3}[a-f0-9-]{16},UUID,g' | sort | uniq -c 
      3 ERROR:  duplicate key value violates unique constraint "unique-dandiset-name"
     68 ERROR    Error calculating assetsSummary               version.py:230
     41 ERROR/ForkPoolWorker-X] dandiapi.api.tasks.validate_version_metadata[UUID]: Error while validating version 500
    123 ERROR/ForkPoolWorker-X] Error calculating assetsSummary
     12 ERROR/ForkPoolWorker-X] Task dandiapi.api.tasks.cancel_zarr_upload[UUID] raised unexpected: TypeError("cancel_zarr_upload() missing 1 required positional argument: 'zarr_id'")
```

- **1**: I think code should be written so that there is no unexpected errors logged, and if error happens there should be some communication to the developers.  Should have not SEntry picked up those?  What other way can we establish channeling of such errors to developers if not through SEntry? (worse comes to worse, I would just write a little script to run above line on a fresh heroku log dump)
- **2**: any among above ERRORs to look into in greater detail?

**Comment by mvandenburgh** [comment]
The validation error logging was actually fixed earlier today, coincidentally. #1152

That error appears to have been caught by sentry, but it got resolved somehow https://sentry.io/organizations/dandiarchive/issues/3301451213/?project=5266078&query=Zarr&statsPeriod=14d

**Comment by yarikoptic** [comment]
oh, indeed curious why/how it got resolved. But I guess it was active for awhile albeit also without attention.

Altogether there is 12 issues in sentry  ATM.  I guess they should be triaged and handled one way or another  (marked to be ignored or dealt with etc), and for some issues to be created here so we do not forget.  E.g. the one I noticed but then forgot about was the `Failed to create DOI 10.80507/dandi.202493/0.220628.1501` .

Altogether I think we should aim for 0 + setup notification for sending daily summary email if the count > 0.  Is that feasible to achieve?

**Comment by waxlamp** [comment]
> Altogether I think we should aim for 0

Agreed. We don't have a good process for dealing with Sentry reports, and part of the reason is that there are many, many false positives currently being sent. This has been on my radar for some time, and perhaps now that there is a lot of attention on it, this is a good time to tackle it.

> + setup notification for sending daily summary email if the count > 0. Is that feasible to achieve?

I would argue *not* to do this. Sentry already sends emails for each issue, and the problem with Sentry is not that we don't get enough notifications about it--it's simply that we don't have good *process*.

My plan here (started long ago, and never really followed up on by me) is to get the team educated in Sentry best practices, and then set up a process by which we pay more attention to the error reports, and slowly make the codebase send cleaner and fewer errors to Sentry, with fewer and fewer false positives. Just as we have a process for refining and clearing a backlog of issues via GitHub, I'd like to have a similar backlog approach to transferring items from Sentry into GitHub, or solving them outright (by, e.g., identifying false positives, or otherwise preventing non-errors from reaching Sentry).

**Comment by yarikoptic** [comment]
> I would argue not to do this. Sentry already sends emails for each issue

has anyone seen an email for the `cancel_zarr_upload` issue? I have received none although there were 54 events.

> ... set up a process by which we pay more attention to the error reports, and slowly make the codebase send cleaner and fewer errors to Sentry, with fewer and fewer false positives

isn't it the point of sentry to be able to mark some issues as "ignore" and then new incidents will not be notified about and that issue would not be listed among active (pardon my ignorance in sentry functioning/practices)?

how many among current 12 false positives? could we mark them as the ones to "ignore"?

**Comment by waxlamp** [comment]
The procedure is indeed to mark those false positives as "ignore", but the *fix* would be to look at changing the code to not send those false error reports in the first place. This is what happened with, e.g., the log lines marked `ERROR` when they were actually reporting `INFO` about validation errors (which are not actually Sentry-level errors).

I am not sure how many are false positives, but enough are that we have not been spending a lot of time dealing with reports from Sentry, due to not trusting the quality of those reports. I'm suggesting that we will create a process whereby we can both eliminate the volume of false positives, and also deal with the true positives (the way Mike and Jake have been doing for several recent error reports).

**Comment by yarikoptic** [comment]
> I am not sure how many are false positives, but enough ...

how many is "enough"?  within the past 30 days I see [25 altogether](https://sentry.io/organizations/dandiarchive/issues/?environment=production&project=5266078&query=&statsPeriod=30d) and [16 unresolved](https://sentry.io/organizations/dandiarchive/issues/?environment=production&project=5266078&query=is%3Aunresolved&statsPeriod=30d) . That is less than 1 issue per day (I wish my life as that issue less ;-) ) and some of them are likely about the two sides of the same coin like the one about 

[ValueError dandiapi.api.tasks.validate_version_metadata](https://sentry.io/organizations/dandiarchive/issues/2748717875/?environment=production&project=5266078&query=is%3Aunresolved&statsPeriod=30d)
Provided metadata has no schema version

which is also reported to be 4mo old.   So it looks to me just needing some TLC, even if not establishing some ideal sentry workflow.  I am still interested if anyone saw an email about `cancel_zarr_upload`?  if yes, and ignored , then it is a matter of fatigue to all those false positives? then we better deal with them ASAP even if such workflow wouldn't be ideal.

**Comment by waxlamp** [comment]
> > I am not sure how many are false positives, but enough ...
> 
> how many is "enough"? within the past 30 days I see [25 altogether](https://sentry.io/organizations/dandiarchive/issues/?environment=production&project=5266078&query=&statsPeriod=30d) and [16 unresolved](https://sentry.io/organizations/dandiarchive/issues/?environment=production&project=5266078&query=is%3Aunresolved&statsPeriod=30d) . That is less than 1 issue per day (I wish my life as that issue less ;-) ) and some of them are likely about the two sides of the same coin like the one about
> 

I don't know how many is "enough", but I'm sure you have had the experience of false positives screwing up a reporting process. Only a few false positives leads to distrust in the mechanisms.

> [ValueError dandiapi.api.tasks.validate_version_metadata](https://sentry.io/organizations/dandiarchive/issues/2748717875/?environment=production&project=5266078&query=is%3Aunresolved&statsPeriod=30d) Provided metadata has no schema version
> 
> which is also reported to be 4mo old. So it looks to me just needing some TLC, even if not establishing some ideal sentry workflow.

Agreed that TLC is needed, and as with many such cleanup processes, TLC to clean up the current state of things, followed by putting in place a process to prevent further messes is the long term solution.

> I am still interested if anyone saw an email about `cancel_zarr_upload`? if yes, and ignored , then it is a matter of fatigue to all those false positives? then we better deal with them ASAP even if such workflow wouldn't be ideal.

I forwarded you the email I received about `cancel_zarr_upload()`. I believe we didn't look closely at that report due to exactly the false positive based distrust I'm talking about here.

I agree it is important for us to clean this up and begin paying better attention to these reports. I'm aiming my team towards that.

**Comment by danlamanna** [comment]
Closing this issue, the error in question was caught but unnoticed, probably due to https://en.wikipedia.org/wiki/Alarm_fatigue. Sentry is in a much better place now with only a small handful of issues we need to tackle. The constant influx of sentry issues and heroku alarms are mostly gone now.
