### ISSUE TITLE
Revoke presigned URLs and delete uploaded files on upload cancel

### ISSUE THREAD

**Issue by AlmightyYakob** [dandi/dandi-archive#1162]
There's a TODO in the zarr `upload_cancel` method:
https://github.com/dandi/dandi-archive/blob/312c8a25f656ff21e5146156a370c335e7a8cc7c/dandiapi/api/models/zarr.py#L259-L267

This means that currently, if somebody starts an upload, uploads some of the files, and then cancels the upload, a couple of things can happen:

1. The presigned urls that were originally given still exist, so they can still be used to upload data
2. Since the already uploaded files aren't deleted, the zarr checksum won't match the expected value, since there source of truth when computing those checksums is the files in S3, not our database.

To prevent this, upon upload cancel, all presigned URLs should be revoked, and all uploaded files should be deleted.

**Comment by yarikoptic** [comment]
> and all uploaded files should be deleted.

but this would not guarantee that checksum would match now (unless we start using bucket versioning, store all versionIds for all files involved in the upload, and delete only back to those versionIds), since e.g. if I re-upload file `/X` with a new version, and cancel that upload, and completely remove `/X` - previously computed checksum (while original version of `/X` existed) would no longer be valid. Hence, as in https://github.com/dandi/dandi-archive/issues/1138#issuecomment-1176452290, we should "schedule" that zarr for re-ingestion upon cancellation.

And that is why I do not really see the point of deleting partially uploaded to zarr files. (again, unless we make it smart and rely on deleting back to previous version, but even then not sure if there is sufficient benefit)

+1 on revoking presigned URLs in case of canceling the upload.

**Comment by AlmightyYakob** [comment]
> From my brief reading online, it seems that you can't really revoke a presigned URL. Until I understand the threat model better, I can't say how that complicates things.

That's true, I suppose we wouldn't have a way to revoke those objects. Maybe we don't need to do anything here, I was just posting this to correspond to the TODO in the code. 

This isn't necessarily a "threat", it just allows the possibility for inconsistency in our system.

**Comment by yarikoptic** [comment]
I guess so. And we already have a good number of checking tasks which fill up the https://api.dandiarchive.org/dashboard/ (not sure if anyone monitors/reacts to it though) so that would be the logical place to visualize that one too.

**Comment by waxlamp** [comment]
Closing as moot since the Zarr overhaul has been deployed.
