### ISSUE TITLE
Enable "delete dandiset" operation from web UI

### ISSUE THREAD

**Issue by waxlamp** [dandi/dandi-archive#1171]
The API allows for deletion of dandisets with no published versions, and this functionality is available through `dandi-cli` (see https://github.com/dandi/dandi-archive/issues/993#issuecomment-1177692053), so it should be available from the web interface as well.

**Comment by waxlamp** [comment]
@satra, @yarikoptic, is this a valid idea?

**Comment by yarikoptic** [comment]
In principle - yes. But it might be one of those cases of "security through obscurity" or "no harm due to difficulty" where I would prefer to keep it *not so easy* to delete dandisets.  After all such action should not happen regularly.  Moreover, it is only the dandisets without published versions which could be removed by mortal users since published versions can be removed only by admins (at least according to doc strings) .

**Comment by satra** [comment]
i would add this button (available for relevant draft dandisets), with the relevant secondary check like type in `permanently delete <dandi identifier>` as a secondary string action.

**Comment by waxlamp** [comment]
This is a dupe of #719; closing in favor of that.
