### ISSUE TITLE
Investigate/Remove use of SHA-256 checksumming 

### ISSUE THREAD

**Issue by AlmightyYakob** [dandi/dandi-archive#1213]
According to a discussion with @yarikoptic there doesn't seem to be a compelling reason for / use of asset sha-256 checksums. In our effort to remove technical debt, this should be addressed.

**Comment by waxlamp** [comment]
@yarikoptic, @satra, I'd like to confirm that the SHA-256 checksum isn't being used for anything, as hinted by Yarik in yesterday's meeting. Since this is one of the current processes causing memory issues / slowdowns in the deployment, we need to be aggressive about getting rid of it if it's not accruing any real value to users at the moment.

**Comment by satra** [comment]
i'm not sure we should get rid of it, and any computation of sha256 should not require additional memory other than the reference stream being used. it can take time, but a job itself should not require more memory. i think having multiple digests are useful. there is no good answer to how many digests to have. but before we remove it, it would be good to know what aspect of this is causing issues.

i can write a python function that reads and computes sha256 without much memory requirements at all. i thought that's how it was implemented. and this is why it's a separate worker as well so as to not interfere with other api processes. also this should only trigger on blob upload so metadata changes should not affect this worker.

**Comment by danlamanna** [comment]
Closing this - sha256 isn't causing memory issues and there is a genuine business need for it (dedupe).
