### ISSUE TITLE
auto import authors from paper

### ISSUE THREAD

**Issue by bendichter** [dandi/dandi-archive#1423]
There have been several times that we need to add many authors to a dandiset from a e.g. biorxiv paper, e.g. https://www.biorxiv.org/content/10.1101/2021.07.28.454025v2. Adding each author manually can be tedious and error-prone. It would be really nice if, when adding a paper as a related resource, we have the option to automatically import all of the authors as authors of the dandiset. I suspect there is some biorxiv open REST API that would make this feasible.

This would be a cool feature but I would say low priority.

**Comment by yarikoptic** [comment]
FWIW, for any DOI it should be feasible to get the reference with authors

```
❯ curl --silent -L -d "" --header "Accept: application/vnd.citationstyles.csl+json; charset=utf-8" https://doi.org/10.1101/2021.07.28.454025 | jq .author | head -n 20
[
  {
    "name": "MICrONS Consortium",
    "sequence": "first",
    "affiliation": []
  },
  {
    "ORCID": "http://orcid.org/0000-0002-4681-6342",
    "authenticated-orcid": false,
    "given": "J. Alexander",
    "family": "Bae",
    "sequence": "additional",
    "affiliation": []
  },
  {
    "given": "Mahaly",
    "family": "Baptiste",
    "sequence": "additional",
    "affiliation": []
  },
...
```
so indeed it would be nice to add some "query DOI for metadata" button and populate title and authors fields if they are still empty.

**Comment by bendichter** [comment]
thanks for the proof-of-concept, @yarikoptic!

**Comment by weiglszonja** [comment]
Thanks @yarikoptic! 

This is not a full solution, just posting this snipped that worked for me to update the raw metadata for a dandiset:


```python
from dandi.dandiapi import DandiAPIClient
from dandischema.models import Person
api = DandiAPIClient()
api.authenticate(token="your_api_token")
ds = api.get_dandiset(dandiset_id)

meta_raw = ds.get_raw_metadata() 
# make the changes to the metadata e.g. append contributors (in DANDI format)
meta_raw["contributor"].extend(additional_contributors_list)
# try validate contributors, fix errors if any (can also embed in try except)
[Person(**meta_raw['contributor'][i]) for i in range(len(meta_raw['contributor']))]
# set raw metadata to this metadata, overwrites existing metadata on web interface!
ds.set_raw_metadata(meta_raw)
```


To get the additional_contributors_list something like minimal like this can work: 

```python
additional_contributors_list = []
for author_record in author_records:
    author_dandi_record = dict(
        name=f'{author_record["family"]}, {author_record["given"]}',
        roleName=['dcite:Author'],
        schemaKey='Person',
        affiliation=[],
        includeInCitation=True,
    )
    if "ORCID" in author_record:
        author_dandi_record.update(identifier=author_record['ORCID'].split("\\/")[-1])
    
    additional_contributors_list.append(author_dandi_record)
        
```

**Comment by satra** [comment]
thanks @weiglszonja .  @yarikoptic - perhaps this can be added as a utility to function to the CLI.  shall we move this over to the CLI ? we can also consider this as an example notebook in case people wanted to adapt for other sources of such info.

**Comment by yarikoptic** [comment]
Since most likely we would want indeed to validate, show, ask re-confirmation to change dandiset metadata, could indeed be implemented there.  

But note -- we generally do not touch dandiset metadata (e.g. in `dandi upload` etc). So it could also be done on the server / web-UI -- I think it might relate to looking up authors by ORCID to fill out the information - https://github.com/dandi/dandi-archive/issues/772 .  Both would need some frontend support for 

- give user an option to enter some ID (DOI or ORCID or later some term URLs etc), 
- request metadata from external resource
- harmonize obtained response to our schema
- display to the user seeking for confirmation on the action to be performed (e.g. display old and new value for the metadata record to be added)
- perform tune up of the metadata record upon confirmation.

If we want to have "request" step implemented in Python, we could expose through API server I guess, and require authenticated session to limit.  Then web UI would be simplified to just minimal UI oriented implementation.

**Comment by yarikoptic** [comment]
@weiglszonja is the last version of the snippet you have used? if not - could you please update it (can just edit inplace that comment I guess)

**Comment by weiglszonja** [comment]
@yarikoptic thats the one. The `author_records` list of dict was actually copied from the result of running the `curl` snipppet that you sent.

**Comment by waxlamp** [comment]
Closing in favor of https://github.com/dandi/dandi-cli/issues/1280.
