### ISSUE TITLE
dandiset with long title

### ISSUE THREAD

**Issue by bendichter** [dandi/dandi-archive#1475]
https://dandiarchive.org/dandiset/000362 has a title that is too long for the schema which has a max char length of 150. How did this occur? How is it possible to change the title to be this long? The metadata editor prevents you from making the title more than 150 characters. Was this done using the `DandiAPIClient`?

**Comment by bendichter** [comment]
So anyone using the API can create invalid metadata accidentally, which makes it difficult to include this dandiset in searches? Is that really what we want? Is there at least a warning? It seems like something like character length could be checked pretty easily.

**Comment by waxlamp** [comment]
> So anyone using the API can create invalid metadata accidentally, which makes it difficult to include this dandiset in structured searches? Is that really what we want? Is there at least a warning? It seems like something like character length could be checked pretty easily.

The workflow is currently centered around preparing draft dandisets for publishing, which means that metadata must be updated through whatever means (currently: web app, API) and then validated asynchronously. Note that you can "accidentally" have bad metadata even through the web app (e.g., by simply forgetting to set a license). So, in answer to "is that really what we want?", the answer is (at least currently) "yes" (but see final paragraph below).

When you ask about a warning, I believe you mean as part of the API call that, e.g., sets the title. The warning right now is through two routes: one is (again) the web app, which does show the validation failure on that dandiset; the other is the fact that an attempt to publish the dandiset through the API will fail. These things form more of a backstop than anything. The latter item specifically is not a good way to tell programmatically whether the dandiset has validation errors (since you may not actually be ready to publish it). And because of our focus on a web app centric workflow, it would be too costly to equip every API route with synchronous validation.

I am not sure what you meant about including the dandiset in structured searches. What limitation around searches are you referring to? I believe draft dandisets do come up in search.

On a larger note: I'm sensing that you're imagining or engaging in a workflow different from the web app focused one we've been optimizing everything for. If that's true, what kind of workflow are you looking at in which the asynchronous validation step causes a problem? Depending on what you're trying to do, we may be able to identify a workaround.

(In the meantime, I'm going to close this issue but if we identify a more specific problem we can open a new one to address it.)

**Comment by bendichter** [comment]
@waxlamp By structured searches, I mean that I am using the Python API to search over the metadata of the dandiset or the metadata of the assets, e.g. as a simple example, if I wanted to find all NWB dandisets that contained data on mice and NWB files:

```python
from dandi.dandiapi import DandiAPIClient
from tqdm.notebook import tqdm

client = DandiAPIClient()
dandisets = list(client.get_dandisets())

nwb_dandisets = []

for dandiset in tqdm(dandisets):
    metadata = dandiset.get_raw_metadata()
    if any(
        x['identifier'] == 'RRID:SCR_015242'
        for x in dandiset.get_raw_metadata()['assetsSummary'].get('dataStandard', {})
    ) and (any("mouse" in x["name"].lower() for x in metadata["assetsSummary"].get("species", [])):
        nwb_dandisets.append(dandiset)
print(len(nwb_dandisets))
```

I've had to make a few adaptations already here:
1. I'm using `dandiset.get_raw_metadata()`. I can't use `dandiset.get_metadata()` because this fails whenever a dandiset does not validate.
2. All of the code where I am digging into the metadata dictionary makes assumptions about the form of the metadata. If these assumptions are not met, even for a single dandiset, it could cause the entire query to fail, so either I need to wrap everything in try/excepts, or I need to build in logic to handle all of the exceptions where the metadata does not fit the schema.
