### ISSUE TITLE
ownership of dandiset 36

### ISSUE THREAD

**Issue by bendichter** [dandi/dandi-archive#1482]
@jeromelecoq has a strange situation with https://dandiarchive.org/dandiset/000036

When he goes to the Manage Owners modal, it says he owns the dandiset:

<img width="1437" alt="image001" src="https://user-images.githubusercontent.com/844306/217372382-f9cb20f8-ab7e-4a01-8bd0-4b649c5f660c.png">

However, he is unable to add an owner or alter the metadata, and this dandiset does not show up in his "My Dandisets" page.

**Comment by jeromelecoq** [comment]
This is accurate. I also cannot edit the license or modify tags.

**Comment by satra** [comment]
jerome was one of our early adopters and there are two jerome's in the user database. daniel used to run a migration script to move an older jerome (placeholder jerome) to a new github user, when we migrated from girder to django. 

the more interesting part is that neither jerome shows up in the owner search box. it's possible because of a conflict internally.

@AlmightyYakob is this something you can take a look at?

**Comment by waxlamp** [comment]
I just removed Jerome and re-added him--it's a bit janky because indeed two Jeromes show up in the list of users when I search. But @jeromelecoq, perhaps you can see if you have proper access now. If not, we can try something a little more drastic--namely, removing the "placeholder" account from the system and then trying once more. I'll wait for you to report back before we do anything like that.

**Comment by waxlamp** [comment]
@jeromelecoq, can you verify whether you now effectively own this Dandiset?

**Comment by jeromelecoq** [comment]
yes
