### ISSUE TITLE
Avoid "gaps" in dandiset ID increment

### ISSUE THREAD

**Issue by yarikoptic** [dandi/dandi-archive#1513]
Finally the mystery of https://github.com/dandi/dandi-archive/issues/627 is resolved, kudos to @waxlamp to tracking it down.
Now that we know that we simply can't rely on postgres ID sequence generation, we should produce one ourselves, possibly with some completely negligible performance effect from needed locking or whatever - creation of a new dandiset ID is a very rare event.  Gaps are confusing and misleading as on the number of dandisets ever created, so I think we should have it resolved.

**Comment by asmacdo** [comment]
In a dandi meeting today, it was reported that these increments are caused by postgress batching (under the hood) and any fix for this would cost us performance, reliability, etc.

The value of the sequential ids is not critical, so the general feeling was that we should just accept that the IDs will be somewhat higher than the total number of dandisets. (Even with this issue fixed, deleted datasets will still cause this problem). 

Reporting is handled elsewhere, and accurately produces usage data. Recommend that we close unless @yarikoptic has a cool idea :)

**Comment by satra** [comment]
as long as we know that gaps are ok, i care less about minting ids. if we hit closer to 999999 we can consider other options.

**Comment by yarikoptic** [comment]
> if we hit closer to 999999 we can consider other options.

I think more like 100000 should be our `id` of a concern -- meaning that likely we under appreciated the severity of the issue since it would mean that within x10 of that time we run into 999999 and really need to think about it.

As to me - most likely the solution is likely very trivial, https://stackoverflow.com/questions/9984196/postgresql-gapless-sequences some recipes/ideas, but indeed not worth the hassle ATM.
