### ISSUE TITLE
Unable to access manifest/download files from embargoed dataset through the webapp

### ISSUE THREAD

**Issue by alejoe91** [dandi/dandi-archive#1729]
Hi guys,

We are experiencing a problem with embargo datasets. Either trying to access the MANIFEST or download a single file from the web-app results in this error:

![image](https://github.com/dandi/dandi-archive/assets/17097257/d6bf6e26-32bc-4831-9559-f8052841f244)

**Comment by satra** [comment]
@mvandenburgh - any ideas why this would change?

**Comment by mvandenburgh** [comment]
I encountered the same bug when trying to view that asset, and I was able to fix it by logging out and logging back in again through the UI. @alejoe91 I would recommend trying that for the time being, and let us know if that doesn't work.

@satra we've seen this issue before with the Django admin page; what appears to happen is somehow the user's session expires for server-rendered pages before it does so for REST endpoints/anything accessed through the Vue client. I thought this was only impacting the admin pages, but because that asset manifest page is actually a server rendered page as well, it's affecting that as well. I'll dig up the issue for that and add this info, as it seems like that should be prioritized if it's affecting regular users.

**Comment by alejoe91** [comment]
@mvandenburgh thanks! loggin out and in again did the trick!

**Comment by satra** [comment]
thank you @mvandenburgh  - perhaps we should add this into an FAQ section on the handbook or in a discussion.

**Comment by yarikoptic** [comment]
> @satra we've seen this issue before with the Django admin page; what appears to happen is somehow the user's session expires for server-rendered pages before it does so for REST endpoints/anything accessed through the Vue client. I thought this was only impacting the admin pages,

- smells like it might be related to https://github.com/dandi/dandi-archive/issues/1701 ?
