### ISSUE TITLE
Confusing information on DLP "Contributors", Metadata's Contributors, Owners

### ISSUE THREAD

**Issue by yarikoptic** [dandi/dandi-archive#2023]
For a sample dandiset 000029 (feel to torture it - it is our sample one in main archive):

![image](https://github.com/user-attachments/assets/e4698347-2b54-433a-a886-cc712ddf9ef5)

so there is long list of various Owners, and then only Mike listed among Contributors. Going to "Metadata" I expected at least "Dandiset Contributors" to correspond to Contributors on DLP but it is now the case - those do not relate to Contribuors or Owners. 

![image](https://github.com/user-attachments/assets/b85abb4e-37c4-4cb3-8459-7409ef637b1f)

- How such divergence could happen? I thought that DLP is taking Contributors from the metadata record
- How exactly "Owners" are defined/stored?

**Comment by waxlamp** [comment]
Confusing indeed! So I don't know what happened here, but as soon as I edited the contributors list in any way and saved the metadata, things became correct on the DLP. Unfortunately, without a way to reproduce the divergence, it will be hard or impossible to know what went wrong.

> How such divergence could happen?

I guess one way is that long ago, someone edited the metadata and saved it, and somehow the trigger to recompute something was lost, and things in the `Version` model somehow got out of sync. (This is a wild guess and doesn't track with the way these systems work.)

> I thought that DLP is taking Contributors from the metadata record

It should be, and now is.

> How exactly "Owners" are defined/stored?

The owners and contributors are totally separate listings.

Owners for a Dandiset are defined as the DANDI users who have the `owner` permission on the Dandiset: https://github.com/dandi/dandi-archive/blob/117b7ef8a3d83f7983c5027569c6eec27a6146e3/dandiapi/api/models/dandiset.py#L77-L79

You can see how new owners are assigned in this block of code: https://github.com/dandi/dandi-archive/blob/117b7ef8a3d83f7983c5027569c6eec27a6146e3/dandiapi/api/models/dandiset.py#L93-L97

By contrast, contributors are set as records in the metadata. Some subtleties here:
- Owners _must be DANDI users_ while no such restriction exists for contributors
- Owners are a property of the _Dandiset_, while contributors are a metadata entry and thus are associated to a _Version_.

In general, owners and contributors are not the same set. For example, ownership might be given to all members of a lab (even new ones) so that someone can, e.g., toil away at improving the metadata, etc. Or (as is the case for 000029) perhaps Dandibot needs to be an owner, but clearly would not be a contributor.

Since owners of a Dandiset fulfill a different role from the contributors to a Dandiset, it makes sense to administer them separately.

I am going to close the issue because there's nothing actionable we can do here, but if this issue recurs, please re-open.

**Comment by satra** [comment]
@waxlamp - one potential consideration is whether audit is tracking metadata changes. that may help at least track down the chain of changers.

**Comment by waxlamp** [comment]
> @waxlamp - one potential consideration is whether audit is tracking metadata changes. that may help at least track down the chain of changers.

Audit does track metadata changes. Every time the metadata is changed, the new metadata, the user that performed the change, the Dandiset in question, and the time of the change are all recorded in the audit record.

**Comment by yarikoptic** [comment]
uff -- I got into observing this odd case and was surprised to find it still present, just "differently".  We have Mike listed as the first contributor on https://dandiarchive.org/dandiset/000029/draft

![image](https://github.com/user-attachments/assets/90a9ad03-1dc8-4902-8f3c-688496985394)

but in meditor he is not there

![image](https://github.com/user-attachments/assets/95d51170-6de5-4fbb-ba68-1455992c8724)

if order is reversed there -- `Smith, John` is for Mike?

Metadata brings even more "fun" -- there it is "Smith**y**" not "Smith"!

```shell
❯ curl --silent -X 'GET' 'https://api.dandiarchive.org/api/dandisets/000029/versions/draft/' -H 'accept: application/json' | jq '.contributor'
[
  {
    "name": "VanDenburgh, Mike",
    "roleName": [
      "dcite:ContactPerson"
    ],
    "schemaKey": "Person",
    "includeInCitation": true
  },
  {
    "url": "https://dandiarchive.org",
    "name": "Test Org",
    "email": "michael.vandenburgh@kitware.com",
    "roleName": [
      "dcite:Sponsor"
    ],
    "schemaKey": "Organization",
    "identifier": "https://ror.org/000000000",
    "contactPoint": [],
    "includeInCitation": true
  },
  {
    "name": "Smithy, John",
    "roleName": [],
    "schemaKey": "Person",
    "affiliation": [],
    "includeInCitation": false
  },
  {
    "name": "Last, First",
    "roleName": [
      "dcite:Author",
      "dcite:ContactPerson"
    ],
    "schemaKey": "Person",
    "identifier": "0000-0003-3456-2493",
    "affiliation": [
      {
        "name": "An Institution",
        "roleName": [],
        "schemaKey": "Affiliation",
        "contactPoint": [],
        "includeInCitation": false
      }
    ],
    "includeInCitation": true
  }
]
```

so I am totally confused on how DLP "Contributors" rendered and then where meditor got the "Smith"... may be from another version?

**Comment by satra** [comment]
i see the correct contributors in meditor:

<img width="1221" alt="image" src="https://github.com/user-attachments/assets/704fe426-d68a-42fc-a38d-cc8f75b580d9">

**Comment by yarikoptic** [comment]
I do now too!... I have reproduced now
- go to default DLP (non draft -- released)
- open meditor - in contributors 3 ppl
- close meditor
- switch to draft
- open meditor -- in contributors still 3 ppm

**Comment by satra** [comment]
it's a browser cache issue - if you refresh it does fix itself.

**Comment by yarikoptic** [comment]
user should not need to refresh every page he/she visits every time -- I am just navigating the website and ending up (reproducibly) at the wrong metadata record in meditor. There is some wrong state carried out through the session.

**Comment by yarikoptic** [comment]
FWIW -- reproduced in Brave too.  Seems like going to another version among available does not change the "version" of metadata meditor is going to open -- it opens the one page was opened for. E.g. go to https://dandiarchive.org/dandiset/000029/0.210712.1903 with a single author, switch to another version, draft or not, open meditor

**Comment by yarikoptic** [comment]
But overall it is a different issue from original difference between different categories, will refile
