### ISSUE TITLE
Add `Visualize in Neurosift` on Dandiset Landing Page

### ISSUE THREAD

**Issue by kabilar** [dandi/dandi-archive#2039]
## Current state
Neurosift is available for NWB files on DANDI and when in the file browser can be accessed for a single asset by selecting the `External Services` menu.  However, it takes many clicks to get to a Neurosift page.

## Feature request
I would suggest that we also add a `Visualize in Neurosift` button on the landing page of Dandisets that contain NWB files.  This will help surface this tool so that more users see it.  Each Dandiset on Neurosift has a corresponding "summary" page of all the assets which can be linked to from the DLP (e.g. https://neurosift.app/?p=/dandiset&dandisetId=001065&dandisetVersion=draft).

Perhaps we can add this button under the `Dandiset Actions` section:
<img height="256" alt="image" src="https://github.com/user-attachments/assets/c30340fd-85cc-4a6d-babf-48dd09ce8237">

cc @magland @bendichter

**Comment by magland** [comment]
@kabilar I'm in favor. :)

**Comment by yarikoptic** [comment]
me too!  I just want us to ensure that we implement such specification in a generic "fashion".

<details>
<summary>Notes on a potential design</summary> 

 ATM we decide on allowing for neurosift simply given the filename `.nwb` extension.  But at the dandiset level we do not have in our summary file extensions, we have "Data standards" an in particular

```
  "assetsSummary": {
...
    "dataStandard": [
      {
        "name": "Neurodata Without Borders (NWB)",
        "schemaKey": "StandardsType",
        "identifier": "RRID:SCR_015242"
      }
    ],
```

so IMHO the decision should be based on that. But we might like to add to dandischema mapping to IDs like we did in unfinished

- https://github.com/dandi/dandi-cli/pull/958/files
 
We might later also add apps which work on BIDS datasets etc. Hence let's extend our specification/list of external services we coded in https://github.com/dandi/dandi-archive/blob/HEAD/web/src/views/FileBrowserView/FileBrowser.vue#L319 to 

1. specify the `target` ("asset" vs "dataset"; default to "asset"); 
2. rename `regex` into `path_regex` unless we want to add regexing based on dandiset id (makes little sense besides possible blacklisting, but then better be explicit)
  - we can even apply limitation by size at "dataset" level but not sure if there is a use case to limit??
3. in dandi-schema add shorter `id` to standards, i.e. `NWB` or `BIDS` instead of extended "name". Create a mapping from those ids to identifiers
4. add `data_standards` list (as *any* of those) to trigger based on those (instead of regex)
   - a nuisance - not every standard might have RRID, E.g. for OME-Zarr we are adding/using a DOI https://github.com/dandi/dandi-schema/pull/252/files

so here we would have something like 

```
  {
    name: 'Neurosift',
    path_regex: /\.nwb$/,
    maxsize: Infinity,
    endpoint: 'https://neurosift.app?p=/nwb&url=$asset_dandi_url$&dandisetId=$dandiset_id$&dandisetVersion=$dandiset_version$', // eslint-disable-line max-len
  },
  {
    name: 'Neurosift',
    target: 'dataset',
    data_standards: ['NWB'],
    endpoint: 'https://neurosift.app?FIXMEHERE&dandisetId=$dandiset_id$&dandisetVersion=$dandiset_version$', // eslint-disable-line max-len
  },
```
or smth like that ;-)
</details>

**Comment by bendichter** [comment]
The endpoint can simply be:

```
https://neurosift.app/?p=/dandiset&dandisetId=$dandiset_id$&dandisetVersion=$dandiset_version$
```

e.g.: https://neurosift.app/?p=/dandiset&dandisetId=000582&dandisetVersion=draft

**Comment by yarikoptic** [comment]
anyone knows enough of Vue to prototype a solution? ;-)

**Comment by magland** [comment]
> anyone knows enough of Vue to prototype a solution? ;-)

I can work on it next week.

**Comment by magland** [comment]
See #2041
