### ISSUE TITLE
allow for exact path matching in dandisets_versions_assets_list and unify `path*` options

### ISSUE THREAD

**Issue by yarikoptic** [dandi/dandi-archive#444]
somewhat relates to https://github.com/dandi/dandi-api/issues/422 for `dandisets_versions_assets_paths_read` where situation is somewhat opposite: there is both `path` and `path_prefix` which are used as a `path` really (which should end with `/`, but as I just commented on there -- it accepts without now and causes different behavior) and not `path_prefix`.

in `dandisets_versions_assets_list` there is only `path` but it is used really as `path_prefix`. So to check for an asset path, users (like dandi-cli) need to loop through all assets which start with that prefix as done here: https://github.com/dandi/dandi-cli/blob/457c1e519c3daa75f729f686e963e637e5a78e91/dandi/dandiapi.py#L510 to select the one (if any) which matches that exact path.  Not too difficult to see that it might be a VERY expensive for heavy datasets while looking at some specific path which is common prefix to other directories (e.g. an asset under path `sub` at top level).

I think we should harmonize behavior/options across end points.  One choice:

- harmonize to have `path` (exact) and `path_prefix` (the prefix) across end points
- that would require then
  - changing `path` to be `path_prefix` in `dandisets_versions_assets_list` for current logic (**breaking change**)
  - adding handling for exact `path` matching
  - adding errorring out if both `path` and `path_prefix` provided (we are still weak in error reporting/handling)
 
an alternative:

- have `path` (only) and add `path_format={prefix,exact}`
- I kinda like this one more, since 
  - expandable: we could even add later `regex` (limitless capabilities ;) ) , `suffix` (find all .nwb assets?!)
  - backward compatible for `dandisets_versions_assets_list`
  - no need for checking combinatorics of options

**Comment by waxlamp** [comment]
> somewhat relates to #422 for `dandisets_versions_assets_paths_read` where situation is somewhat opposite: there is both `path` and `path_prefix` which are used as a `path` really (which should end with `/`, but as I just commented on there -- it accepts without now and causes different behavior) and not `path_prefix`.
> 
> in `dandisets_versions_assets_list` there is only `path` but it is used really as `path_prefix`. So to check for an asset path, users (like dandi-cli) need to loop through all assets which start with that prefix as done here: https://github.com/dandi/dandi-cli/blob/457c1e519c3daa75f729f686e963e637e5a78e91/dandi/dandiapi.py#L510 to select the one (if any) which matches that exact path. Not too difficult to see that it might be a VERY expensive for heavy datasets while looking at some specific path which is common prefix to other directories (e.g. an asset under path `sub` at top level).
> 

The situation has evolved since this issue was filed. The two endpoints have separate uses:
- `dandisets_versions_assets_paths` (without the trailing `_read` now) takes a dandiset and version and an exact path, which is taken to be a "folder" path. It returns a list of assets and "folders" directly residing in that "folder". As such, this endpoint has no need for a path prefix parameter. Note that the parameter is incorrectly named `path_prefix`, which is something that needs to be fixed.
- `dandisets_versions_assets_list` no longer takes both `path` and `path_prefix` parameters, only `path`, and returns a paginated list of all assets whose name begins with that value. (This parameter is also misnamed and should be called `path_prefix`.) The endpoint also takes a `glob` parameter which is applied as a filter to the results--more on this below.

> I think we should harmonize behavior/options across end points. One choice:
> 
> * harmonize to have `path` (exact) and `path_prefix` (the prefix) across end points

Note that due to the evolving specialties of the two endpoints, we no longer have a need to "unify" these parameters--they are no longer both present in each endpoint.

> * that would require then
>   
>   * changing `path` to be `path_prefix` in `dandisets_versions_assets_list` for current logic (**breaking change**)

Agreed; see note above.

>   * adding handling for exact `path` matching

This request now only applies to `dandisets_versions_assets_list` (because `dandisets_versions_assets_paths` is now designed to *only* work with exact paths). It is already almost possible by specifying the exact path name in the `glob` parameter.

The "almost" comes from a subtlety in how the glob functionality works. `glob` takes a string that may contain one or more `*` characters, meant to match zero or more characters in each place it appears. But you can also supply a `*`-less string, which has the effect of matching that string anywhere in the path. Imagine you are looking for an asset `/path/to/asset.json` and you supply that string in the `glob` parameter (while leaving `path` blank). If that file exists, the endpoint will score a hit. The "almost" comes from the fact that if you also had some other asset `/extra/path/to/asset.json/blah` (in which "asset.json" appears as a "folder"), this asset would also be returned by the endpoint. This is something we can fix in the way that globs are handled.

>   * adding errorring out if both `path` and `path_prefix` provided (we are still weak in error reporting/handling)
> 

This is not needed, due to both parameters not appearing together in these endpoints.

> an alternative:
> 
> * have `path` (only) and add `path_format={prefix,exact}`
> * I kinda like this one more, since
>   
>   * expandable: we could even add later `regex` (limitless capabilities ;) ) , `suffix` (find all .nwb assets?!)
>   * backward compatible for `dandisets_versions_assets_list`
>   * no need for checking combinatorics of options

This also is not needed for the same reason.

A quick note on adding `regex`--this is a dangerous idea because it opens up the archive to ReDoS attacks without providing anything that solves our existing problems. (This is generally the case for any system adding general regex capabilities to its external interfaces.)

To conclude, since this discussion has exposed some bugs, I plan to close this in favor of the following issues:
- #1562 
- #1563
