### ISSUE TITLE
Make Asset/Version.validation_errors blankable in admin UI

### ISSUE THREAD

**Issue by dchiquito** [dandi/dandi-archive#509]
Both `Version` and `Asset` have a field `validation_errors` that doesn't work nicely in the admin UI. Since it isn't marked as `blank`, it can't be left empty when editing an `Asset`/`Version` in the UI, even though it should be.

**Comment by waxlamp** [comment]
@dchiquito, why can't you just set it to `[]`?

**Comment by brianhelba** [comment]
Check out [this field](https://github.com/girder/django-girder-utils/blob/587919e4c7b48b67624be40df3389d02380c69bb/girder_utils/db.py#L9). It won't directly solve this problem, but it'll show where you can override if you want additional validation.

Otherwise, [since an empty list is considered a blank value](https://github.com/django/django/blob/205f67cd5bea242fac6b0380fa26570505d07dcb/django/core/validators.py#L14), you'll have to set `blank=True`.

**Comment by waxlamp** [comment]
This seems to have been fixed (see [asset.py](https://github.com/dandi/dandi-archive/blob/master/dandiapi/api/models/asset.py#L126) and [version.py](https://github.com/dandi/dandi-archive/blob/master/dandiapi/api/models/version.py#L49)).
