### ISSUE TITLE
zarr issues from cli discussion

### ISSUE THREAD

**Issue by satra** [dandi/dandi-archive#674]
- [x] dandiset size doesn't take zarr asset size into account
- [x] zarr content url should point to s3 location (and zarr proxy api end point when that is ready). but the s3 prefix should also be there like other assets.
- [x] move code for zarr checksum compute to dandischema
- [x] needs API (endpoint) to list individual components of a zarr archive to simplify/robustify download; ideally those records should come with minimal metadata (path, size, mtime; mtime could be the time when upload finalized for that file I guess) (added by @yarikoptic channeling https://github.com/dandi/dandi-cli/issues/852#issuecomment-1011348765).

**Comment by dchiquito** [comment]
The size field definitely should be taking the zarr assets into account, I will look into that.

The content URL should be resolved by https://github.com/dandi/dandi-api/pull/678.

checksum compute move is coming soon.

**Comment by dchiquito** [comment]
@yarikoptic The `/zarr/{zarr_id}.zarr/{path}` endpoint should suffice for zarr file browsing. For directories, it returns something like:
```
{
  "directories": [
    "https://api-staging.dandiarchive.org/api/zarr/79bb04a0-3f1b-46ae-8821-1071fc69ed6e.zarr/0",
    "https://api-staging.dandiarchive.org/api/zarr/79bb04a0-3f1b-46ae-8821-1071fc69ed6e.zarr/1",
    "https://api-staging.dandiarchive.org/api/zarr/79bb04a0-3f1b-46ae-8821-1071fc69ed6e.zarr/2",
    "https://api-staging.dandiarchive.org/api/zarr/79bb04a0-3f1b-46ae-8821-1071fc69ed6e.zarr/3",
    "https://api-staging.dandiarchive.org/api/zarr/79bb04a0-3f1b-46ae-8821-1071fc69ed6e.zarr/4",
    "https://api-staging.dandiarchive.org/api/zarr/79bb04a0-3f1b-46ae-8821-1071fc69ed6e.zarr/5"
  ],
  "files": [
    "https://api-staging.dandiarchive.org/api/zarr/79bb04a0-3f1b-46ae-8821-1071fc69ed6e.zarr/.zattrs",
    "https://api-staging.dandiarchive.org/api/zarr/79bb04a0-3f1b-46ae-8821-1071fc69ed6e.zarr/.zgroup"
  ]
}
```

For files, it returns a redirect to the object in S3.

This endpoint uses the content in the `.checksum` files, so it doesn't have any metadata. If you need last modified time, you could always do a HEAD request on the object to get the last modified date.

**Comment by yarikoptic** [comment]
oh, cool -- then it is a non issue at large. Thanks! Marking it with checkmark, let's continue in dandi-cli on this item.

**Comment by yarikoptic** [comment]
> @yarikoptic - you can also get checksums at different levels so you can only download pieces that have differing checksums.

@satra @dchiquito is the entire tree of checksums exposed in API somewhere?  The only end point I think of -- aforementioned `/zarr/{zarr_id}.zarr/{path}` -- doesn't provide it.  I guess that is where checksum for that subtree could be provided in addition to "directories" and "files".

**Comment by jwodder** [comment]
@dchiquito 

> If you need last modified time, you could always do a HEAD request on the object to get the last modified date.

Attempting a HEAD request with `curl -IsS https://api-staging.dandiarchive.org/api/zarr/79bb04a0-3f1b-46ae-8821-1071fc69ed6e.zarr/.zattrs` results in "405 Method Not Allowed".

**Comment by yarikoptic** [comment]
Those are redirects, we would need to take it from the redirected url response I guess?

**Comment by jwodder** [comment]
@yarikoptic That doesn't work either.  If I do `curl -isS https://api-staging.dandiarchive.org/api/zarr/79bb04a0-3f1b-46ae-8821-1071fc69ed6e.zarr/.zattrs`, copy the "Location" header, and then do `curl -IsS $LOCATION`, I get "403 Forbidden".

**Comment by dchiquito** [comment]
@yarikoptic @jwodder How about modifying the shape of `/zarr/{zarr_id}.zarr/{path}` so that it looks like:
```json
{
  "directories": [
    "https://api-staging.dandiarchive.org/api/zarr/79bb04a0-3f1b-46ae-8821-1071fc69ed6e.zarr/0/",
    "https://api-staging.dandiarchive.org/api/zarr/79bb04a0-3f1b-46ae-8821-1071fc69ed6e.zarr/1/",
    "https://api-staging.dandiarchive.org/api/zarr/79bb04a0-3f1b-46ae-8821-1071fc69ed6e.zarr/2/",
    "https://api-staging.dandiarchive.org/api/zarr/79bb04a0-3f1b-46ae-8821-1071fc69ed6e.zarr/3/",
    "https://api-staging.dandiarchive.org/api/zarr/79bb04a0-3f1b-46ae-8821-1071fc69ed6e.zarr/4/",
    "https://api-staging.dandiarchive.org/api/zarr/79bb04a0-3f1b-46ae-8821-1071fc69ed6e.zarr/5/"
  ],
  "files": [
    "https://api-staging.dandiarchive.org/api/zarr/79bb04a0-3f1b-46ae-8821-1071fc69ed6e.zarr/.zattrs",
    "https://api-staging.dandiarchive.org/api/zarr/79bb04a0-3f1b-46ae-8821-1071fc69ed6e.zarr/.zgroup"
  ],
  "checksums": {
    "0": "51d3b348723ec82cf1b222a65724664b",
    "1": "51d3b348723ec82cf1b222a65724664b",
    "2": "51d3b348723ec82cf1b222a65724664b",
    "3": "51d3b348723ec82cf1b222a65724664b",
    "4": "51d3b348723ec82cf1b222a65724664b",
    "5": "51d3b348723ec82cf1b222a65724664b",
    ".zattrs": "51d3b348723ec82cf1b222a65724664b",
    ".zgroup": "51d3b348723ec82cf1b222a65724664b"
  },
  "checksum": "7bc57f61a65f96a20b27b1edf9626668"
}
```
`checksums` would contain a checksum for every child of the directory. `checksum` would be the checksum of the current directory.

`LastModified` isn't obtainable without a HEAD request to S3. Hypothetically, you could query the API server, take the `Location` header of the 302 redirect, strip off the query parameters to get the URL of the object, then do a HEAD with that URL (no presigning). However, that would not work for embargoed zarr data, since that requires the presigning. I think the CLI should be able to make do with using checksum comparisons to determine when something needs to be updated.

**Comment by dchiquito** [comment]
https://github.com/dandi/dandi-archive/issues/746 would also be an acceptable solution, assuming that clients will follow redirects for HEAD requests as they do for GETs.

**Comment by jwodder** [comment]
@dchiquito Adding checksums to `/zarr/{zarr_id}.zarr/{path}` sounds good.

**Comment by yarikoptic** [comment]
> `checksums` would contain a checksum for every child of the directory. `checksum` would be the checksum of the current directory.

I see potential benefits of  including "every child" checksum, but since that would duplicate information within child's own `checksum` field, I wonder if it would better be avoided, and only `checksum` field for this directory itself be kept? (if checksums for children are needed, should be fetched if were not already)

**Comment by yarikoptic** [comment]
Thank you @dchiquito , makes sense. The only concern is that there is now more to `fsck`:
- consistency of checksums for directories 
- consistency in listings (`checksums` keys must be `==` to union of keys in `directories` and `files`).  This one is trivial, but still -- duplication, thus should be checked IMHO.

How/when should we run such fsck's across the entire archive? how could we avoid redoing checksuming a specific .zarr ? (I guess need some 'fsckLast' DB entry for each zarr)

**Comment by dchiquito** [comment]
@yarikoptic I think I don't understand the issue you are concerned about. #802 is basically just a modification to the API surface. It grabs the checksum data from the `.checksum` file along with the subfile and subdirectory information.

"fsck" is handled during zarr file upload or delete, and all tainted `.checksum` files in the tree are updated accordingly. We could add a management command to do a `fsck`-like check on demand if that's a concern, but the `.checksum` file is assumed to always be up to date.

Are you asking about fscking the CLI side data? That's not something I have put much thought into.

**Comment by yarikoptic** [comment]
@dchiquito Thank you for the clarification -- I think I have indeed missed the fact that it is solely reporting on "API surface" which otherwise comes from the same data contained in `.checksum` files on S3.  That is where duplication already exists for directories, and exposing that data via API indeed doesn't make it worse.

s3 checksums information duplication: good that `upload or delete` handle necessary checks for consistency etc, but that is IMHO the point of `fsck` to check if state remains consistent whenever it is expected that it should or must be consistent. So, we might need to add such checks later on, while may be any code working with those checksums and having access to both checksums could check if they are consistent and alert user (who can alert us) that something is odd.  E.g., although unlikely, AFAIK mismatch could potentially happen in a race condition between "read" and "write" operations for a .zarr if we allow for zarr to mutate in place.

BTW, since our bucket is versioned -- why don't we provide versionIds in urls for files?

**Comment by dchiquito** [comment]
> why don't we provide versionIds in urls for files?

[django-s3-file-field](https://github.com/girder/django-s3-file-field) doesn't do that out of the box ¯\\\_(ツ)\_/¯

**Comment by dchiquito** [comment]
> dandiset size doesn't take zarr asset size into account

This was resolved in https://github.com/dandi/dandi-archive/pull/798

>  zarr content url should point to s3 location (and zarr proxy api end point when that is ready). but the s3 prefix should also be there like other assets.

I believe this was resolved in https://github.com/dandi/dandi-archive/pull/678/files

> move code for zarr checksum compute to dandischema

This was resolved in https://github.com/dandi/dandischema/pull/109/files
