### ISSUE TITLE
Do not hardcode "dandiarchive.org"

### ISSUE THREAD

**Issue by yarikoptic** [dandi/dandi-archive#793]
I am working a local instance and registered a new dandiset.  Upon visiting that dandiset metadata record I see a URL which directs to dandiarchive.org:
![DeepinScreenshot_select-area_20200313110207](https://user-images.githubusercontent.com/39889/76632785-1be88600-651a-11ea-868a-02836eeebc28.png)

Ideally it should have been `https://localhost:8092/dandiset/000000/draft` in my case and worked (it doesn't ATM (separate issue dandi/dandi-api#273)

**Comment by yarikoptic** [comment]
remains the case - on staging

![image](https://github.com/dandi/dandi-archive/assets/39889/b3bfdb8c-556d-4b05-bced-e34a9f55da1a)

**Comment by yarikoptic** [comment]
still the case for me on https://gui-staging.dandiarchive.org/dandiset/214362?pos=1 . Could you please add this issue to the board/doc for "multiple DANDI instances" -- I feel it is a minor issue which could be addressed easily by someone with basic Vue skill.

**Comment by kabilar** [comment]
Thanks @yarikoptic.  Is the remaining issue with regards to the URL that is returned from the `Share` button?  Did you notice any other incorrect links?

<img width="500" alt="image" src="https://github.com/user-attachments/assets/583807ed-3daf-499f-a979-a8d679d8a138">

The `Download` button URL was fixed in #1810 and returns the correct URL:

<img width="486" alt="image" src="https://github.com/user-attachments/assets/2406362b-7083-41ad-990a-2ad01f1a7633">

I added this to the [Engineering Core](https://docs.google.com/document/d/1R2gb9oz7UyaYW4LIrvhqpXqLQ4mZKv4rtddQASTZUtc/edit?tab=t.0) Google Doc, which is where I am tracking all the issues for this target.

**Comment by yarikoptic** [comment]
looking at 

```
❯ git grep dandiUrl
web/src/utils/constants.ts:const dandiUrl = 'https://dandiarchive.org';
web/src/utils/constants.ts:  dandiUrl,
web/src/views/DandisetLandingView/DownloadDialog.vue:  const dandiUrl = `DANDI:${identifier}`;
web/src/views/DandisetLandingView/DownloadDialog.vue:  const url = window.location.origin == 'https://dandiarchive.org' ? dandiUrl : generalUrl;
web/src/views/DandisetLandingView/ShareDialog.vue:import { dandiUrl } from '@/utils/constants';
web/src/views/DandisetLandingView/ShareDialog.vue:        return `${dandiUrl}/dandiset/${currentDandiset.value?.dandiset.identifier}/${currentVersion.value}`;
```

and 

```
web/src/utils/constants.ts:const dandiUrl = 'https://dandiarchive.org';
web/src/views/DandisetLandingView/DownloadDialog.vue:  const url = window.location.origin == 'https://dandiarchive.org' ? dandiUrl : generalUrl;
```

it might be the only one left but I would not bed on that ;)

**Comment by kabilar** [comment]
Thanks @yarikoptic.  I discussed this issue with @aaronkanzer and he will tackle it.
