### ISSUE TITLE
update github committish pointers in ui

### ISSUE THREAD

**Issue by satra** [dandi/dandi-archive#849]
this points to the old repo.

![image](https://user-images.githubusercontent.com/184063/151036194-ba77ded9-0c6d-4e6e-91a9-5c3bb39fdb4a.png)

**Comment by satra** [comment]
also 2021 --> 2022

**Comment by waxlamp** [comment]
Noticed this yesterday, will file a quick fix. Thanks @satra!

As for the copyright year, can we switch to something like `(c) 2016-present DANDI` so that we don't need to update it every year? Copyright law seems to only require the word/symbol for "copyright", the year of first publication, and the copyright holder's name.

**Comment by satra** [comment]
> can we switch to something like `(c) 2016-present DANDI `

sure.

**Comment by satra** [comment]
should say 2019 - present

**Comment by waxlamp** [comment]
> should say 2019 - present

Thanks--terrible guess on my part 😆
